export const ADMIN_NAV = [
  { href: '/admin', label: 'Overview' },
  { href: '/admin/mylink', label: 'My Link' },
  { href: '/admin/summary', label: 'Weekly Summary' },
  { href: '/admin/promoters', label: 'Promoters' },
  { href: '/admin/university', label: 'University' },
  { href: '/admin/guests', label: 'Guests' },
  { href: '/admin/guestlists', label: 'Guestlists' },
  { href: '/admin/blackout', label: 'Blackout' },
  { href: '/admin/whats-on', label: "What's On" },
  { href: '/admin/venues', label: 'Venues' },
  { href: '/admin/staff', label: 'Staff' },
  { href: '/reception', label: 'Door Check-in' },
  { href: '/admin/leaderboards', label: 'Leaderboards' },
  { href: '/admin/tiers', label: 'Tiers'